# Generated by Django 6.0.1 on 2026-01-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_promocode_order_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
