# Generated by Django 6.0.1 on 2026-01-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_created_at_customuser_updated_at_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='body',
        ),
    ]
