# Generated by Django 6.0.1 on 2026-01-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_created_at_customuser_updated_at_and_more'),
        ('users', '0005_remove_message_recipient_chat_message_chat'),
    ]

    operations = [
    ]
