# Generated by Django 6.0.1 on 2026-01-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
