# Generated by Django 6.0.1 on 2026-01-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teammember_facebook_teammember_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
    ]
