# Generated by Django 6.0.1 on 2026-01-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_comment_date_remove_product_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
