# Generated by Django 6.0.1 on 2026-01-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_comment_options_and_more'),
        ('products', '0007_delete_comment'),
    ]

    operations = [
    ]
